// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Algo7",
            "email": "tools@algo7.tools"
        },
        "license": {
            "name": "GNU GENERAL PUBLIC LICENSE Version 3",
            "url": "https://raw.githubusercontent.com/algo7/day-planner-gpt-data-portal/main/LICENSE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/apikey": {
            "get": {
                "description": "Returns a page to get the initial API key. If the initial password has expired, it redirects to the home page.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Get API Key Page",
                "responses": {
                    "200": {
                        "description": "Render the API key form page",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "302": {
                        "description": "Redirect to the home page if the initial password has expired",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Error getting initial password from Redis",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Generates a new API key and stores it in Redis with a TTL of 7 days. If the initial password has expired, it redirects to the home page.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Generate API Key",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Password for API key generation",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "API key: {apiKey}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "302": {
                        "description": "Redirect to the home page if the initial password has expired",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Incorrect password",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Error getting initial password or generating API key",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/google/auth": {
            "get": {
                "description": "Redirects to the Google OAuth2 authentication page.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OAuth2"
                ],
                "summary": "OAuth2 Redirect for Google",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization code from Google OAuth2 provider",
                        "name": "code",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "302": {
                        "description": "Redirect to a predefined route after successful authorization",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "No authorization code found in the request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Error loading OAuth2 config or exchanging code for token",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/google/oauth_redirect": {
            "get": {
                "description": "Handles the callback from Google OAuth2 authentication, exchanging the authorization code for an access token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OAuth2"
                ],
                "summary": "OAuth2 Redirect for Google",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization code from Google OAuth2 provider",
                        "name": "code",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "302": {
                        "description": "Redirect to a predefined route after successful authorization",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "No authorization code found in the request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Unable to read client secret file or parse it to config",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/outlook/auth": {
            "get": {
                "description": "Redirects to the Outlook OAuth2 authentication page.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OAuth2"
                ],
                "summary": "Get Outlook Auth Page",
                "responses": {
                    "302": {
                        "description": "Redirect to the Outlook OAuth2 authentication page.",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Error loading OAuth2 config",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/outlook/oauth_redirect": {
            "get": {
                "description": "Handles the callback from Outlook OAuth2 authentication, exchanging the authorization code for an access token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OAuth2"
                ],
                "summary": "OAuth2 Redirect for Outlook",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization code from Outlook OAuth2 provider",
                        "name": "code",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "302": {
                        "description": "Redirect to a predefined route after successful authorization",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "No authorization code found in the request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Error loading OAuth2 config or exchanging code for token",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Fiber Example API",
	Description:      "day-planner-gpt-data-portal",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
